server:
  port: 8081
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
  cloud:
    loadbalancer:
      ribbon:
        enable: false

feign:
  client:
    config:
      externalService:
        url: localhost:8082